// ============================================================
// player/MooshakCharacter.js
// Mooshak (the divine mouse vāhana) — loads a detailed GLB model
// generated by Blender. Falls back to procedural if GLB fails.
// ============================================================

import * as THREE from "three";
import { assetManager } from "../core/AssetManager.js";

export class MooshakCharacter {
  constructor() {
    this.root = new THREE.Group();
    this.root.name = "MooshakRoot";
    this.root.visible = false;
    this.speed = 5.5;
    this.facing = 0;
    this.targetFacing = 0;
    this.loaded = false;
    this.scene = null;
    this._walkPhase = 0;
    // Build a procedural fallback immediately (replaced when GLB loads).
    this._buildProcedural();
  }

  async load() {
    try {
      const gltf = await assetManager.loadGLB("mooshak/mooshak.glb");
      this.scene = gltf.scene;
      // Scale to ~0.6m tall (mouse is small).
      const box = new THREE.Box3().setFromObject(this.scene);
      const size = new THREE.Vector3();
      box.getSize(size);
      if (size.y > 0.001) {
        const scale = 0.6 / size.y;
        this.scene.scale.setScalar(scale);
        this.scene.position.x -= (box.min.x + box.max.x) * 0.5 * scale;
        this.scene.position.z -= (box.min.z + box.max.z) * 0.5 * scale;
        this.scene.position.y -= box.min.y * scale;
      }
      // Shadows.
      this.scene.traverse((o) => {
        if (o.isMesh) {
          o.castShadow = true;
          o.receiveShadow = true;
        }
      });
      // Remove the procedural fallback.
      if (this._procedural) {
        this.root.remove(this._procedural);
        this._procedural.traverse((o) => {
          if (o.isMesh) {
            if (o.geometry) o.geometry.dispose();
            if (o.material) o.material.dispose();
          }
        });
        this._procedural = null;
      }
      this.root.add(this.scene);
      this.loaded = true;
      console.log("[Mooshak] GLB loaded successfully");
    } catch (e) {
      console.warn("[Mooshak] GLB load failed, using procedural fallback:", e);
      // Keep the procedural fallback that was built in the constructor.
    }
    return this;
  }

  _buildProcedural() {
    // Procedural fallback (only used if GLB fails to load).
    const grp = new THREE.Group();
    grp.name = "MooshakProcedural";
    // Body (small egg).
    const bodyGeo = new THREE.SphereGeometry(0.18, 16, 12);
    bodyGeo.scale(1.3, 0.9, 1.0);
    const bodyMat = new THREE.MeshStandardMaterial({
      color: 0x8a5a3a, roughness: 0.7, metalness: 0.0,
    });
    this.body = new THREE.Mesh(bodyGeo, bodyMat);
    this.body.castShadow = true;
    this.body.position.y = 0.18;
    grp.add(this.body);
    // Head.
    const headGeo = new THREE.SphereGeometry(0.13, 16, 12);
    const head = new THREE.Mesh(headGeo, bodyMat);
    head.castShadow = true;
    head.position.set(0.22, 0.24, 0);
    this.head = head;
    grp.add(head);
    // Snout.
    const snoutGeo = new THREE.ConeGeometry(0.05, 0.14, 8);
    const snout = new THREE.Mesh(snoutGeo, new THREE.MeshStandardMaterial({
      color: 0xe8c9a0, roughness: 0.6,
    }));
    snout.rotation.z = -Math.PI / 2;
    snout.position.set(0.34, 0.22, 0);
    head.add(snout);
    snout.position.set(0.12, -0.02, 0);
    // Ears.
    const earGeo = new THREE.SphereGeometry(0.06, 12, 8);
    earGeo.scale(1, 1, 0.2);
    const earMat = new THREE.MeshStandardMaterial({ color: 0xc77b4a, roughness: 0.7 });
    const earL = new THREE.Mesh(earGeo, earMat);
    earL.position.set(-0.02, 0.10, 0.06);
    earL.rotation.y = Math.PI / 2;
    head.add(earL);
    const earR = earL.clone();
    earR.position.z = -0.06;
    head.add(earR);
    // Eyes.
    const eyeGeo = new THREE.SphereGeometry(0.018, 8, 6);
    const eyeMat = new THREE.MeshStandardMaterial({ color: 0x140808, roughness: 0.2 });
    const eyeL = new THREE.Mesh(eyeGeo, eyeMat);
    eyeL.position.set(0.09, 0.04, 0.05);
    head.add(eyeL);
    const eyeR = eyeL.clone();
    eyeR.position.z = -0.05;
    head.add(eyeR);
    // Tail.
    const tailGeo = new THREE.CylinderGeometry(0.012, 0.002, 0.22, 6);
    const tail = new THREE.Mesh(tailGeo, bodyMat);
    tail.position.set(-0.24, 0.18, 0);
    tail.rotation.z = Math.PI / 3;
    grp.add(tail);
    this.tail = tail;
    // Legs.
    const legGeo = new THREE.CylinderGeometry(0.025, 0.02, 0.10, 6);
    this.legs = [];
    const legPositions = [
      [ 0.12, 0.05,  0.07],
      [ 0.12, 0.05, -0.07],
      [-0.10, 0.05,  0.07],
      [-0.10, 0.05, -0.07],
    ];
    for (const p of legPositions) {
      const leg = new THREE.Mesh(legGeo, bodyMat);
      leg.position.set(...p);
      leg.castShadow = true;
      this.body.add(leg);
      this.legs.push(leg);
    }
    // Gold collar.
    const collarGeo = new THREE.TorusGeometry(0.085, 0.012, 8, 16);
    const collarMat = new THREE.MeshStandardMaterial({
      color: 0xffc966, metalness: 1.0, roughness: 0.2,
    });
    const collar = new THREE.Mesh(collarGeo, collarMat);
    collar.position.set(0.18, 0.22, 0);
    collar.rotation.y = Math.PI / 2;
    head.add(collar);
    this.root.add(grp);
    this._procedural = grp;
  }

  setVisible(v) {
    this.root.visible = v;
  }

  setPosition(x, y, z) {
    this.root.position.set(x, y, z);
  }

  setRotation(yaw) {
    this.facing = yaw;
    this.root.rotation.y = yaw;
  }

  faceToward(yaw, dt, speed = 8) {
    this.targetFacing = yaw;
    let diff = this.targetFacing - this.facing;
    while (diff > Math.PI) diff -= Math.PI * 2;
    while (diff < -Math.PI) diff += Math.PI * 2;
    this.facing += diff * (1 - Math.exp(-speed * dt));
    this.root.rotation.y = this.facing;
  }

  update(dt, isMoving) {
    if (isMoving) {
      this._walkPhase += dt * 12;
      if (this.body) {
        this.body.position.y = 0.18 + Math.abs(Math.sin(this._walkPhase)) * 0.02;
      }
      if (this.legs) {
        for (let i = 0; i < this.legs.length; i++) {
          const phase = this._walkPhase + (i % 2) * Math.PI;
          this.legs[i].rotation.x = Math.sin(phase) * 0.4;
        }
      }
      if (this.head) {
        this.head.position.y = 0.24 + Math.sin(this._walkPhase * 0.5) * 0.01;
      }
      if (this.tail) {
        this.tail.rotation.y = Math.sin(this._walkPhase * 0.7) * 0.3;
      }
    } else {
      const t = performance.now() * 0.002;
      if (this.body) {
        this.body.position.y = 0.18 + Math.sin(t) * 0.005;
      }
      if (this.tail) {
        this.tail.rotation.y = Math.sin(t * 0.7) * 0.15;
      }
    }
  }

  dispose() {
    this.root.traverse((o) => {
      if (o.isMesh) {
        if (o.geometry) o.geometry.dispose();
        if (o.material) o.material.dispose();
      }
    });
  }
}

export default MooshakCharacter;
